on:
  repository_dispatch:
    types:
      - deploy-prod-ui
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: cjiis/sabaq
          token: ${{ secrets.GH_PAT }}
          ref: ${{ github.event.client_payload.ref }}
      - uses: actions/checkout@v4
        with:
          repository: cjiis/sabaq-action
          token: ${{ secrets.GH_PAT }}
          path: sabaq-action
      - id: get-ui-build-environment
        uses: ./sabaq-action
        with:
          workflow: get-ui-build-environment
      - uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "17"
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.get-ui-build-environment.outputs.flutterVersion }}
      - run: sudo gem install bundler -v $BUNDLER_VERSION
        env:
          BUNDLER_VERSION: ${{ steps.get-ui-build-environment.outputs.bundlerVersion }}
      - run: bundle install
        working-directory: android
      - run: |
          echo "$GOOGLE_UPLOAD_KEYSTORE_BASE64" | base64 -d > $GITHUB_WORKSPACE/android/upload-keystore.jks &&
          echo "storePassword=$GOOGLE_UPLOAD_KEYSTORE_PASSWORD" >> $GITHUB_WORKSPACE/android/key.properties &&
          echo "keyPassword=$GOOGLE_UPLOAD_KEYSTORE_PASSWORD" >> $GITHUB_WORKSPACE/android/key.properties &&
          echo "keyAlias=upload" >> $GITHUB_WORKSPACE/android/key.properties &&
          echo "storeFile=$GITHUB_WORKSPACE/android/upload-keystore.jks" >> $GITHUB_WORKSPACE/android/key.properties
        env:
          GOOGLE_UPLOAD_KEYSTORE_PASSWORD: ${{ secrets.GOOGLE_UPLOAD_KEYSTORE_PASSWORD }}
          GOOGLE_UPLOAD_KEYSTORE_BASE64: ${{ secrets.GOOGLE_UPLOAD_KEYSTORE_BASE64 }}
      - run: dart run build_runner build
      - run: flutter build appbundle --flavor prod --dart-define=USE_FIREBASE_EMULATOR=false
      - run: bundle exec fastlane prodDeploy
        working-directory: android
        env:
          GOOGLE_PLAY_API_KEY: ${{ secrets.GOOGLE_PLAY_API_KEY }}
