on:
  workflow_dispatch:
    inputs:
      ref:
        required: true
        description: the reference to deploy
jobs:
  build-and-distribute:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: cjiis/sabaq
          token: ${{ secrets.GH_PAT }}
          ref: ${{ github.event.inputs.ref }}
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.8.0"
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
          check-latest: true
      - run: npm i -g firebase-tools
      - run: flutter build web
      - run: firebase --token $FIREBASE_TOKEN -P prod deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
