on:
  release:
    types:
      - released
jobs:
  build-and-distribute:
    runs-on: macos-11
    steps:
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.3"
      - uses: actions/checkout@v2
      - run: bundle install
        working-directory: ios
      - run: flutter build ios --flavor prod --no-codesign
      - run: bundle exec fastlane prodBuildDeploy
        working-directory: ios
        env:
          APPLE_API_KEY: ${{ secrets.APPLE_API_KEY }}
          FASTLANE_MATCH_GIT_KEY: ${{ secrets.FASTLANE_MATCH_GIT_KEY }}
          FASTLANE_MATCH_GIT_PASSWORD: ${{ secrets.FASTLANE_MATCH_GIT_PASSWORD }}
          FASTLANE_KEYCHAIN_PASSWORD: ${{ secrets.FASTLANE_KEYCHAIN_PASSWORD }}
